### ISSUE TITLE
Blank charts

### ISSUE THREAD

**Issue by spanznet** [Manuel83/craftbeerpi3#179]
Just tried a completely fresh install of latest raspbian, git pull cbpi3, and addons: SystemTemp, OneWireAdvanced and Tilt.    Right away any attempt to chart sees this in the app.log:

2018-03-16 20:49:04,993 - ERROR - Exception on /api/logs/f/1 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_classy.py", line 200, in proxy
    response = view(**request.view_args)
  File "/home/pi/craftbeerpi3/modules/logs/endpoints.py", line 85, in get_logs_as_json
    result = map(self.convert_chart_data_to_json, cbpi.get_fermentation_controller(fermenter.logic).get("class").chart(fermenter))
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by spanznet** [comment]
I figured this out.  Because I'm just testing the temp sensors and it's not hooked up to a fridge, I hadn't bothered to set the fermentation logic to hysterisis.  If you leave it unselected the chart won't work.
